# Generated by Django 4.1.5 on 2023-01-29 09:59

from django.db import migrations, models
import django.db.models.deletion
import factory.models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=60, verbose_name='ناحیه')),
            ],
            options={
                'verbose_name': 'ناحیه',
                'verbose_name_plural': 'ناحیه',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=60, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'نوع',
                'verbose_name_plural': 'نوع',
            },
        ),
        migrations.AlterModelOptions(
            name='factoryimagemodel',
            options={'verbose_name': 'ویدیو کارخونه', 'verbose_name_plural': 'ویدیو کارخونه'},
        ),
        migrations.RenameField(
            model_name='factoryimagemodel',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='factorymodel',
            old_name='name',
            new_name='factory_name',
        ),
        migrations.AlterField(
            model_name='factoryimagemodel',
            name='Warnings',
            field=models.TextField(blank=True, verbose_name='هشدار'),
        ),
        migrations.AlterField(
            model_name='factoryimagemodel',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factorymodel', verbose_name='کارخانه'),
        ),
        migrations.AlterField(
            model_name='factoryimagemodel',
            name='factory_image',
            field=models.ImageField(upload_to=factory.models.Profile_image_path, verbose_name='عکس وسیله یا شخص'),
        ),
        migrations.AlterField(
            model_name='factorymodel',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='cameramodel',
            name='area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='factory.areamodel', verbose_name='ناحیه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factoryimagemodel',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='factory.categorymodel', verbose_name='نوع'),
            preserve_default=False,
        ),
    ]
