# Generated by Django 4.1.5 on 2023-01-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_areamodel_categorymodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameramodel',
            options={'verbose_name': ' دوربین ', 'verbose_name_plural': ' دوربین '},
        ),
        migrations.AlterModelOptions(
            name='factoryimagemodel',
            options={'verbose_name': 'عکس کارخانه', 'verbose_name_plural': 'عکس کارخانه'},
        ),
        migrations.AlterModelOptions(
            name='factorymodel',
            options={'verbose_name': 'کارخانه', 'verbose_name_plural': 'کارخانه'},
        ),
        migrations.RemoveField(
            model_name='cameramodel',
            name='area',
        ),
        migrations.AddField(
            model_name='factoryimagemodel',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.areamodel', verbose_name='ناحیه'),
            preserve_default=False,
        ),
    ]
