# Generated by Django 4.1.5 on 2023-02-05 17:35

from django.db import migrations, models
import factory.models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0003_alter_cameramodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaDetect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.SmallIntegerField(verbose_name="ناحیه")),
                ("category", models.CharField(max_length=50, verbose_name="نام شی")),
                ("warning", models.BooleanField(verbose_name="هشدار")),
                ("xyxy", models.CharField(max_length=255, verbose_name="دقت نویسه ها")),
                ("date_read", models.DateField(verbose_name="تاریخ تشخیص")),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        upload_to=factory.models.mainproductFile,
                        verbose_name="تصویر ",
                    ),
                ),
                ("time_read", models.TimeField(verbose_name="زمان قرائت")),
            ],
            options={"verbose_name": "تشخیص ها",},
        ),
    ]
